M48
; DRILL file {KiCad 6.0.10+dfsg-1~bpo11+1} date Sun Feb 19 21:59:10 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-19T21:59:10+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X180.086Y-138.176
X184.15Y-138.176
T0
M30
