M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Thu Apr 13 00:33:39 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-13T00:33:39+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X180.086Y-138.176
X184.15Y-138.176
T0
M30
