M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date Wed Nov 16 14:10:50 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-16T14:10:50+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X180.086Y-138.176
X184.15Y-138.176
T0
M30
